#!/usr/bin/env python
# encoding: utf-8

name = "CO_Disproportionation/groups"
shortDesc = ""
longDesc = """
This family describes reactions of the sort:
Y_rad + [CH]=O <=> Y_H + [C-]#[O+]

atom labels:

  R_rad   +        [CH]=O        <=>     RH     +    [C-]#[O+]

R_rad(*1) + H(*4)C_rad(*3)=O(*2) <=> R(*1)H(*4) + [C-](*3)#[O+](*2)
"""

template(reactants=["Root"], products=["Y_H", "CO_CS"], ownReverse=False)

reverse = "CO_Addition"
reversible = True

reactantNum = 2

productNum = 2

autoGenerated = True

recipe(actions=[
    ['FORM_BOND', '*1', 1, '*4'],
    ['BREAK_BOND', '*3', 1, '*4'],
    ['LOSE_PAIR', '*2', '1'],
    ['GAIN_PAIR', '*3', '1'],
    ['CHANGE_BOND', '*2', 1, '*3'],
    ['LOSE_RADICAL', '*1', '1'],
    ['LOSE_RADICAL', '*3', '1'],
])

entry(
    index = 0,
    label = "Root",
    group = 
"""
1 *3 C                     u1         p0 c0 {2,S} {3,D}
2 *4 [H,F1s,Cl1s,Br1s,I1s] u0         p[0,3] c0 {1,S}
3 *2 [O,S2d]               u0         p2 c0 {1,D}
4 *1 R                     u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 1,
    label = "Root_4R->F",
    group = 
"""
1 *3 C                     u1 p0 c0 {2,S} {3,D}
2 *4 [H,F1s,Cl1s,Br1s,I1s] u0 p[0,3] c0 {1,S}
3 *2 O                     u0 p2 c0 {1,D}
4 *1 F                     u1
""",
    kinetics = None,
)

entry(
    index = 2,
    label = "Root_4R->F_2Br1sCl1sF1sHI1s->F1s",
    group = 
"""
1 *3 C   u1 p0 c0 {2,S} {3,D}
2 *4 F1s u0 p[0,3] c0 {1,S}
3 *2 O   u0 p2 c0 {1,D}
4 *1 F   u1
""",
    kinetics = None,
)

entry(
    index = 3,
    label = "Root_4R->F_N-2Br1sCl1sF1sHI1s->F1s",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 F u1 r0
""",
    kinetics = None,
)

entry(
    index = 4,
    label = "Root_N-4R->F",
    group = 
"""
1 *3 C                        u1         p0 c0 {2,S} {3,D}
2 *4 [H,F1s,Cl1s,Br1s,I1s]    u0         p[0,3] c0 {1,S}
3 *2 O                        u0         p2 c0 {1,D}
4 *1 [C,N,P,H,Si,I,Br,Cl,O,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 5,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s",
    group = 
"""
1 *3 C                        u1         p0 c0 {2,S} {3,D}
2 *4 Cl1s                     u0         p[0,3] c0 {1,S}
3 *2 O                        u0         p2 c0 {1,D}
4 *1 [C,N,P,H,Si,I,Br,Cl,O,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 6,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_4BrCClHINOPSSi->C",
    group = 
"""
1 *3 C    u1         p0 c0 r0 {2,S} {3,D}
2 *4 Cl1s u0         p[0,3] c0 r0 {1,S}
3 *2 O    u0         p2 c0 r0 {1,D}
4 *1 C    u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 7,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C",
    group = 
"""
1 *3 C             u1         p0 c0 {2,S} {3,D}
2 *4 Cl1s          u0         p[0,3] c0 {1,S}
3 *2 O             u0         p2 c0 {1,D}
4 *1 [N,H,Br,Cl,O] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 8,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O",
    group = 
"""
1 *3 C    u1         p0 c0 {2,S} {3,D}
2 *4 Cl1s u0         p[0,3] c0 {1,S}
3 *2 O    u0         p2 c0 {1,D}
4 *1 O    u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 9,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O_4O-u1",
    group = 
"""
1 *3 C    u1 p0 c0 r0 {2,S} {3,D}
2 *4 Cl1s u0 p[0,3] c0 r0 {1,S}
3 *2 O    u0 p2 c0 r0 {1,D}
4 *1 O    u1 r0
""",
    kinetics = None,
)

entry(
    index = 10,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O_N-4O-u1",
    group = 
"""
1 *3 C    u1 p0 c0 r0 {2,S} {3,D}
2 *4 Cl1s u0 p[0,3] c0 r0 {1,S}
3 *2 O    u0 p2 c0 r0 {1,D}
4 *1 O    u2 r0
""",
    kinetics = None,
)

entry(
    index = 11,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O",
    group = 
"""
1 *3 C      u1 p0 c0 {2,S} {3,D}
2 *4 Cl1s   u0 p[0,3] c0 {1,S}
3 *2 O      u0 p2 c0 {1,D}
4 *1 [H,Cl] u1
""",
    kinetics = None,
)

entry(
    index = 12,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O_4ClH->H",
    group = 
"""
1 *3 C    u1 p0 c0 r0 {2,S} {3,D}
2 *4 Cl1s u0 p[0,3] c0 r0 {1,S}
3 *2 O    u0 p2 c0 r0 {1,D}
4 *1 H    u1 r0
""",
    kinetics = None,
)

entry(
    index = 13,
    label = "Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O_N-4ClH->H",
    group = 
"""
1 *3 C    u1 p0 c0 r0 {2,S} {3,D}
2 *4 Cl1s u0 p[0,3] c0 r0 {1,S}
3 *2 O    u0 p2 c0 r0 {1,D}
4 *1 Cl   u1 r0
""",
    kinetics = None,
)

entry(
    index = 14,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s",
    group = 
"""
1 *3 C                        u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H]                  u0         p[0,3] c0 {1,S}
3 *2 O                        u0         p2 c0 {1,D}
4 *1 [C,N,P,H,Si,I,Br,Cl,O,S] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 15,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_4BrCClHINOPSSi->Br",
    group = 
"""
1 *3 C       u1         p0 c0 r0 {2,S} {3,D}
2 *4 [F1s,H] u0         p[0,3] c0 r0 {1,S}
3 *2 O       u0         p2 c0 r0 {1,D}
4 *1 Br      u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 16,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br",
    group = 
"""
1 *3 C            u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H]      u0         p[0,3] c0 {1,S}
3 *2 O            u0         p2 c0 {1,D}
4 *1 [C,N,H,Cl,O] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 17,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_4CClHNO->Cl",
    group = 
"""
1 *3 C       u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H] u0         p[0,3] c0 {1,S}
3 *2 O       u0         p2 c0 {1,D}
4 *1 Cl      u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 18,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl",
    group = 
"""
1 *3 C         u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H]   u0         p[0,3] c0 {1,S}
3 *2 O         u0         p2 c0 {1,D}
4 *1 [C,O,H,N] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 19,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_4CHNO->N",
    group = 
"""
1 *3 C       u1         p0 c0 r0 {2,S} {3,D}
2 *4 [F1s,H] u0         p[0,3] c0 r0 {1,S}
3 *2 O       u0         p2 c0 r0 {1,D}
4 *1 N       u[1,2,3,4] r0
""",
    kinetics = None,
)

entry(
    index = 20,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N",
    group = 
"""
1 *3 C       u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H] u0         p[0,3] c0 {1,S}
3 *2 O       u0         p2 c0 {1,D}
4 *1 [C,O,H] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 21,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 O u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 22,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 O   u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 23,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_5R!H->C",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 O u1 {5,S}
5    C ux r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 24,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C",
    group = 
"""
1 *3 C                      u1         p0 c0 {2,S} {3,D}
2 *4 H                      u0         p[0,3] c0 {1,S}
3 *2 O                      u0         p2 c0 {1,D}
4 *1 O                      u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [N,P,Si,F,I,Br,Cl,O,S] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 25,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_5BrClFINOPSSi->Cl",
    group = 
"""
1 *3 C  u1         p0 c0 r0 {2,S} {3,D}
2 *4 H  u0         p[0,3] c0 r0 {1,S}
3 *2 O  u0         p2 c0 r0 {1,D}
4 *1 O  u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    Cl ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 26,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl",
    group = 
"""
1 *3 C        u1         p0 c0 {2,S} {3,D}
2 *4 H        u0         p[0,3] c0 {1,S}
3 *2 O        u0         p2 c0 {1,D}
4 *1 O        u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [N,O,Br] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 27,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_5BrNO->O",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 O u1 r0 {5,S}
5    O u1 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 28,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O",
    group = 
"""
1 *3 C      u1         p0 c0 {2,S} {3,D}
2 *4 H      u0         p[0,3] c0 {1,S}
3 *2 O      u0         p2 c0 {1,D}
4 *1 O      u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [N,Br] u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 29,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O_5BrN->N",
    group = 
"""
1 *3 C u1         p0 c0 r0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 r0 {1,S}
3 *2 O u0         p2 c0 r0 {1,D}
4 *1 O u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    N u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 30,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O_N-5BrN->N",
    group = 
"""
1 *3 C  u1         p0 c0 r0 {2,S} {3,D}
2 *4 H  u0         p[0,3] c0 r0 {1,S}
3 *2 O  u0         p2 c0 r0 {1,D}
4 *1 O  u[1,2,3,4] r0 {5,[S,D,T,B,Q]}
5    Br u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 31,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_4O-u1",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 O u1 r0
""",
    kinetics = None,
)

entry(
    index = 32,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_N-4O-u1",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 O u2
""",
    kinetics = None,
)

entry(
    index = 33,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O",
    group = 
"""
1 *3 C       u1         p0 c0 {2,S} {3,D}
2 *4 [F1s,H] u0         p[0,3] c0 {1,S}
3 *2 O       u0         p2 c0 {1,D}
4 *1 [C,H]   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 34,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 F1s   u0         p[0,3] c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,H] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 35,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s_4CH->C",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 F1s u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 36,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s_N-4CH->C",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 F1s u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 H   u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 37,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p[0,3] c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 [C,H] u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 38,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4]
""",
    kinetics = None,
)

entry(
    index = 39,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4] {5,[S,D,T,B,Q]}
5    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 40,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl",
    group = 
"""
1 *3 C  u1         p0 c0 {2,S} {3,D}
2 *4 H  u0         p[0,3] c0 {1,S}
3 *2 O  u0         p2 c0 {1,D}
4 *1 C  u[1,2,3,4] {5,[S,D,T,B,Q]}
5    Cl u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 41,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl_Ext-4C-R_6R!H->C",
    group = 
"""
1 *3 C  u1         p0 c0 {2,S} {3,D}
2 *4 H  u0         p[0,3] c0 {1,S}
3 *2 O  u0         p2 c0 {1,D}
4 *1 C  u[1,2,3,4] {5,[S,D,T,B,Q]} {6,S}
5    Cl u0         r0 {4,[S,D,T,B,Q]}
6    C  u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 42,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl_Ext-4C-R_N-6R!H->C",
    group = 
"""
1 *3 C  u1         p0 c0 {2,S} {3,D}
2 *4 H  u0         p[0,3] c0 {1,S}
3 *2 O  u0         p2 c0 {1,D}
4 *1 C  u[1,2,3,4] {5,[S,D,T,B,Q]} {6,S}
5    Cl u0         r0 {4,[S,D,T,B,Q]}
6    Cl u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 43,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl",
    group = 
"""
1 *3 C                     u1         p0 c0 {2,S} {3,D}
2 *4 H                     u0         p[0,3] c0 {1,S}
3 *2 O                     u0         p2 c0 {1,D}
4 *1 C                     u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [C,N,P,Si,F,I,Br,O,S] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 44,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,[S,D,T,B,Q]}
5    O u0         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 45,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O_Sp-5O-4C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,S}
5    O u0         r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 46,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O_N-Sp-5O-4C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,D}
5    O u0         r0 {4,D}
""",
    kinetics = None,
)

entry(
    index = 47,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p[0,3] c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 C     u[1,2,3,4] {5,[S,D,T,B,Q]}
5    [C,F] ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 48,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,D}
5    C ux         {4,D}
""",
    kinetics = None,
)

entry(
    index = 49,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,D}
5    C ux         {4,D} {6,[S,D,T,B,Q]}
6    C ux         {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 50,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_Ext-6R!H-R",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4] {5,D}
5    C   u0         r0 {4,D} {6,[S,D,T,B,Q]}
6    C   u0         r0 {5,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
7    R!H ux         {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 51,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_Sp-6R!H-5CF",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,D}
5    C ux         {4,D} {6,S}
6    C ux         {5,S}
""",
    kinetics = None,
)

entry(
    index = 52,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_N-Sp-6R!H-5CF",
    group = 
"""
1 *3 C u1         p0 c0 {2,S} {3,D}
2 *4 H u0         p[0,3] c0 {1,S}
3 *2 O u0         p2 c0 {1,D}
4 *1 C u[1,2,3,4] {5,D}
5    C ux         {4,D} {6,D}
6    C ux         {5,D}
""",
    kinetics = None,
)

entry(
    index = 53,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-4C-R",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,D} {6,S}
5    C u0 {4,D}
6    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 54,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-4C-R_Ext-6R!H-R",
    group = 
"""
1 *3 C   u1 p0 c0 r0 {2,S} {3,D}
2 *4 H   u0 p[0,3] c0 r0 {1,S}
3 *2 O   u0 p2 c0 r0 {1,D}
4 *1 C   u1 r0 {5,D} {6,S}
5    C   u0 r0 {4,D}
6    C   u0 r0 {4,S} {7,[S,D,T,B,Q]}
7    R!H ux {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 55,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p[0,3] c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 C     u[1,2,3,4] {5,S}
5    [C,F] ux         {4,S}
""",
    kinetics = None,
)

entry(
    index = 56,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R",
    group = 
"""
1 *3 C     u1         p0 c0 {2,S} {3,D}
2 *4 H     u0         p[0,3] c0 {1,S}
3 *2 O     u0         p2 c0 {1,D}
4 *1 C     u[1,2,3,4] {5,S} {6,[S,D,T,B,Q]}
5    [C,F] ux         {4,S}
6    R!H   ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 57,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4] {5,S} {6,[S,D,T,B,Q]}
5    C   ux         {4,S}
6    R!H ux         {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 58,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C_Ext-4C-R",
    group = 
"""
1 *3 C   u1 p0 c0 r0 {2,S} {3,D}
2 *4 H   u0 p[0,3] c0 r0 {1,S}
3 *2 O   u0 p2 c0 r0 {1,D}
4 *1 C   u1 r0 {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
5    C   ux {4,S}
6    R!H ux {4,[S,D,T,B,Q]}
7    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 59,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C_Ext-5C-R",
    group = 
"""
1 *3 C   u1         p0 c0 {2,S} {3,D}
2 *4 H   u0         p[0,3] c0 {1,S}
3 *2 O   u0         p2 c0 {1,D}
4 *1 C   u[1,2,3,4] {5,S} {6,[S,D,T,B,Q]}
5    C   ux         {4,S} {7,[S,D,T,B,Q]}
6    C   ux         {4,[S,D,T,B,Q]}
7    R!H ux         {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 60,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_N-5CF->C",
    group = 
"""
1 *3 C   u1 p0 c0 {2,S} {3,D}
2 *4 H   u0 p[0,3] c0 {1,S}
3 *2 O   u0 p2 c0 {1,D}
4 *1 C   u1 {5,S} {6,[S,D,T,B,Q]}
5    F   u0 {4,S}
6    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 61,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_N-5CF->C_Ext-4C-R",
    group = 
"""
1 *3 C   u1 p0 c0 r0 {2,S} {3,D}
2 *4 H   u0 p[0,3] c0 r0 {1,S}
3 *2 O   u0 p2 c0 r0 {1,D}
4 *1 C   u1 r0 {5,S} {6,[S,D,T,B,Q]} {7,[S,D,T,B,Q]}
5    F   u0 r0 {4,S}
6    R!H ux {4,[S,D,T,B,Q]}
7    R!H ux {4,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 62,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,S}
5    C u0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 63,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,S}
5    C u0 {4,S} {6,[S,D,T,B,Q]}
6    C ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 64,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,S}
5    C u0 {4,S} {6,S}
6    C ux {5,S}
""",
    kinetics = None,
)

entry(
    index = 65,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-5C-R",
    group = 
"""
1 *3 C   u1 p0 c0 r0 {2,S} {3,D}
2 *4 H   u0 p[0,3] c0 r0 {1,S}
3 *2 O   u0 p2 c0 r0 {1,D}
4 *1 C   u1 r0 {5,S}
5    C   u0 r0 {4,S} {6,S} {7,[S,D,T,B,Q]}
6    C   ux {5,S}
7    R!H ux {5,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 66,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,S}
5    C u0 {4,S} {6,S}
6    C u0 {5,S} {7,[S,D,T,B,Q]}
7    C u0 {6,[S,D,T,B,Q]}
""",
    kinetics = None,
)

entry(
    index = 67,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R_Sp-7R!H-6R!H",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 C u1 r0 {5,S}
5    C u0 r0 {4,S} {6,S}
6    C u0 r0 {5,S} {7,S}
7    C u0 r0 {6,S}
""",
    kinetics = None,
)

entry(
    index = 68,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R_N-Sp-7R!H-6R!H",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 C u1 r0 {5,S}
5    C u0 r0 {4,S} {6,S}
6    C u0 r0 {5,S} {7,[B,D,T,Q]}
7    C u0 r0 {6,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 69,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C",
    group = 
"""
1 *3 C u1 p0 c0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 {1,S}
3 *2 O u0 p2 c0 {1,D}
4 *1 C u1 {5,S}
5    C u0 {4,S} {6,[B,D,T,Q]}
6    C ux {5,[B,D,T,Q]}
""",
    kinetics = None,
)

entry(
    index = 70,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C_Sp-6R!H=5C",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 C u1 r0 {5,S}
5    C u0 r0 {4,S} {6,D}
6    C ux {5,D}
""",
    kinetics = None,
)

entry(
    index = 71,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C_N-Sp-6R!H=5C",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 C u1 r0 {5,S}
5    C u0 r0 {4,S} {6,T}
6    C ux {5,T}
""",
    kinetics = None,
)

entry(
    index = 72,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_N-5CF->C",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 C u1 r0 {5,S}
5    F u0 r0 {4,S}
""",
    kinetics = None,
)

entry(
    index = 73,
    label = "Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_N-4CH->C",
    group = 
"""
1 *3 C u1 p0 c0 r0 {2,S} {3,D}
2 *4 H u0 p[0,3] c0 r0 {1,S}
3 *2 O u0 p2 c0 r0 {1,D}
4 *1 H u1 r0
""",
    kinetics = None,
)

tree(
"""
L1: Root
    L2: Root_4R->F
        L3: Root_4R->F_2Br1sCl1sF1sHI1s->F1s
        L3: Root_4R->F_N-2Br1sCl1sF1sHI1s->F1s
    L2: Root_N-4R->F
        L3: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s
            L4: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_4BrCClHINOPSSi->C
            L4: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C
                L5: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O
                    L6: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O_4O-u1
                    L6: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_4BrClHNO->O_N-4O-u1
                L5: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O
                    L6: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O_4ClH->H
                    L6: Root_N-4R->F_2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->C_N-4BrClHNO->O_N-4ClH->H
        L3: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s
            L4: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_4BrCClHINOPSSi->Br
            L4: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br
                L5: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_4CClHNO->Cl
                L5: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl
                    L6: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_4CHNO->N
                    L6: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N
                        L7: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O
                            L8: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_5R!H->C
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C
                                    L10: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_5BrClFINOPSSi->Cl
                                    L10: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl
                                        L11: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_5BrNO->O
                                        L11: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O_5BrN->N
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_Ext-4O-R_N-5R!H->C_N-5BrClFINOPSSi->Cl_N-5BrNO->O_N-5BrN->N
                            L8: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_4O-u1
                            L8: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_4CHO->O_N-4O-u1
                        L7: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O
                            L8: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s_4CH->C
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_2F1sH->F1s_N-4CH->C
                            L8: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C
                                    L10: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R
                                        L11: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl_Ext-4C-R_6R!H->C
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_5R!H->Cl_Ext-4C-R_N-6R!H->C
                                        L11: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O
                                                L13: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O_Sp-5O-4C
                                                L13: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_5BrCFINOPSSi->O_N-Sp-5O-4C
                                            L12: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O
                                                L13: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C
                                                    L14: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_Ext-6R!H-R
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_Sp-6R!H-5CF
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-5CF-R_N-Sp-6R!H-5CF
                                                    L14: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-4C-R
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_Sp-5CCFF=4C_Ext-4C-R_Ext-6R!H-R
                                                L13: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C
                                                    L14: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C
                                                            L16: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C_Ext-4C-R
                                                            L16: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_5CF->C_Ext-5C-R
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_N-5CF->C
                                                            L16: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_Ext-4C-R_N-5CF->C_Ext-4C-R
                                                    L14: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C
                                                        L15: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R
                                                            L16: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C
                                                                L17: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-5C-R
                                                                L17: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R
                                                                    L18: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R_Sp-7R!H-6R!H
                                                                    L18: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_Sp-6R!H-5C_Ext-6R!H-R_N-Sp-7R!H-6R!H
                                                            L16: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C
                                                                L17: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C_Sp-6R!H=5C
                                                                L17: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_5CF->C_Ext-5C-R_N-Sp-6R!H-5C_N-Sp-6R!H=5C
                                                    L14: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_4CH->C_Ext-4C-R_N-5R!H->Cl_N-5BrCFINOPSSi->O_N-Sp-5CCFF=4C_N-5CF->C
                                L9: Root_N-4R->F_N-2Br1sCl1sF1sHI1s->Cl1s_N-4BrCClHINOPSSi->Br_N-4CClHNO->Cl_N-4CHNO->N_N-4CHO->O_N-2F1sH->F1s_N-4CH->C
"""
)

forbidden(
    label = "O2d",
    group = 
"""
1 *2 O u0 {2,D}
2 *3 O u0 {1,D}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "OS_XH_birad_singlet",
    group = 
"""
1 *3 [O,S] u0 p3 {2,[S,D,T]}
2 *2 R!H   ux {1,[S,D,T]} {3,S}
3 *4 H     u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "O_Orad",
    group = 
"""
1 *2 O u0 {2,S} {3,S}
2 *3 O u1 {1,S}
3 *4 H u0 {1,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_N_birad_singlet",
    group = 
"""
1 *3 N   u0 p2 {2,[S,D]}
2 *2 R!H ux {1,[S,D]} {3,S}
3 *4 H   u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_birad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p1 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

forbidden(
    label = "XH_quadrad_singlet",
    group = 
"""
1 *3 [C,Si] u0 p2 {2,[S,D,T]}
2 *2 R!H    ux {1,[S,D,T]} {3,S}
3 *4 H      u0 {2,S}
""",
    shortDesc = """""",
    longDesc = 
"""

""",
)

