# For conda build
package:
  name: rmgdatabase
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python >=3.7
  run:
    - python >=3.7

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-database
  license: MIT
  summary: "Database for RMG: a program for automatically generating kinetic models of chemical reaction mechanisms."
